### PR TITLE
Fixes net exchanges not always appearing in the graph when changing selected time

### LINKED ISSUE #5066: Fix issue with graphs and net exchanges - they come and go when dragging the time slider instead of always being there
The exchanges are not always staying like they did before the app rewrite.
This issue should have a video showing the bug :)

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Issue

Closes #5066

## Description

Due to the way we looked at what exchanges should appear in the breakdown graph (and the breakdown "table" too), we would only show exchanges if there was data for that specific timestamp - even though the graph shows all 24 hours.

### Preview

See before and after in this video:

https://user-images.githubusercontent.com/3296643/226741749-7b0bda1e-6634-4782-ba2d-9cbd8a7c94ef.mp4

### Double check

- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

File: web/src/features/charts/bar-breakdown/utils.ts [hunk 1]
```diff
@@ -179,10 +180,16 @@ export const getExchangesToDisplay = (
...
-    : [];
+  // get all exchanges for the given period
+  const allExchangeKeys = new Set<string>();
+  for (const state of Object.values(zoneStates)) {
+    for (const key of Object.keys(state.exchange)) {
+      allExchangeKeys.add(key);
+    }
+  }
+  const uniqueExchangeKeys = [...allExchangeKeys];
+
```
Comment (madsnedergaard) [inline web/src/features/charts/bar-breakdown/utils.ts:191]: Added this part to find unique exchanges across timestamps. It could probably be done cleaner, but it works ¯\\\_(ツ)\_/¯

Comment (VIKTORVAV99) [reply web/src/features/charts/bar-breakdown/utils.ts:191]: It's weird there is no filter function on a set, if there where we could avoid the secondary constant declaration and the conversion to a array.

File: web/src/features/charts/hooks/useBarElectricityBreakdownChartData.ts [hunk 2]
```diff
@@ -44,7 +44,7 @@ export default function useBarBreakdownChartData() {
   const exchangeKeys = getExchangesToDisplay(
     zoneId,
     isAggregateToggled,
-    currentData.exchange
+    zoneData?.zoneStates
```
Comment (VIKTORVAV99) [inline web/src/features/charts/hooks/useBarElectricityBreakdownChartData.ts:47]: Will zoneData not always be defined?

File: web/src/features/charts/hooks/useBreakdownChartData.ts [hunk 3]
```diff
@@ -37,20 +37,19 @@ export const getLayerFill = (
...
+  if (isLoading || isError || !zoneData || !zoneId) {
     return { isLoading, isError };
   }
 
   const exchangesForSelectedAggregate = getExchangesToDisplay(
-    currentData.zoneKey,
+    zoneId,
     isAggregateToggled,
-    currentData.exchange
+    zoneData?.zoneStates
```
Comment (VIKTORVAV99) [inline web/src/features/charts/hooks/useBreakdownChartData.ts:52]: Same goes here, just adding a comment so we don't forget this one if we change the other one.

File: web/src/features/charts/bar-breakdown/utils.test.ts
Comment (VIKTORVAV99) [inline web/src/features/charts/bar-breakdown/utils.test.ts:1]: It's great to see some more tests added!

**Review by VIKTORVAV99 — COMMENTED** [review]
Nice work!

This was probably our biggest (visual) bug in the frontend!

File: web/src/features/charts/hooks/useBarElectricityBreakdownChartData.ts (hunk 2 above)
Comment (madsnedergaard) [reply web/src/features/charts/hooks/useBarElectricityBreakdownChartData.ts:47]: Yes, good point! :)

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

File: web/src/features/charts/bar-breakdown/utils.ts (hunk 1 above)
Comment (madsnedergaard) [reply web/src/features/charts/bar-breakdown/utils.ts:191]: Yeah, it is a bit messy. We could alternatively gather everything into one array, send it to a new Set() and back to remove non-unique keys, and then use that. In the end it's more or less the same though, so don't think it matters much :)
