### PR TITLE
Fix 6203 tooltip overflows behind screen

### LINKED ISSUE #6203: Tooltip overflows behind the top of the screen
**Describe the bug**
Tooltip goes out of bound

**To Reproduce**
1. Click on a country
2. Scroll the country panel down
3. However on a production mode high up on the screen

**Expected behavior**
Tooltip should not overflow behind the top of the screen

**Screenshots**
image

**Desktop (if relevant):**
 - OS: MacOS
 - Browser Chrome

### PR DESCRIPTION
**Pull request by PmplCode**
## Issue

Closes #6203 , although it is my first time taking part on an open source project and i would like guidance.
## Description

tooltip remains visible everytime even with scrolled screen.
### Preview

https://www.linkedin.com/posts/eloipampliegajose_opensource-frontenddev-electricitymaps-activity-7153079821013508096-yzqW
### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

File: web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx [hunk 1]
```diff
@@ -38,6 +38,13 @@ function BarBreakdownChart() {
     y: number;
   } | null>(null);
 
+  const [headerHeight, setHeaderHeight] = useState<number>(0);
+
+  useEffect(() => {
+    const height = document.querySelectorAll('header')[0].offsetHeight;
+    setHeaderHeight(height * 1.1);
+  }, [window.innerWidth, window.innerHeight]);
+
```
Comment (VIKTORVAV99) [inline web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx:47]:
```suggestion
  const [headerHeight, setHeaderHeight] = useState<number>(0);

  useEffect(() => {
    const height = document.querySelector('header').offsetHeight;
    setHeaderHeight(height * 1.1);
  }, [window.innerWidth, window.innerHeight]);

```
Since you are grabbing the first one anyhow let's just use querySelector() instead querySelectorAll().

File: web/src/features/charts/elements/AreaGraph.tsx [hunk 2]
```diff
@@ -211,6 +211,13 @@ function AreaGraph({
     [setGraphIndex, setSelectedLayerIndex]
   );
 
+  const [headerHeight, setHeaderHeight] = useState<number>(0);
+
+  useEffect(() => {
+    const height = document.querySelectorAll('header')[0].offsetHeight;
+    setHeaderHeight(height * 1.1);
+  }, [window.innerWidth, window.innerHeight]);
+
```
Comment (VIKTORVAV99) [inline web/src/features/charts/elements/AreaGraph.tsx:220]: This seems to be identical to the code in the other file, would be good to extract it to a function so it can be reused instead of duplicated.

**Review by VIKTORVAV99 — COMMENTED** [review]
This works great for the changed tooltips!

However this also affects the exchange tooltips as well so would be good if we could change those too.

I also left some suggestions that could simplify the code.

**Comment by madsnedergaard** [comment]
Hey @PmplCode, let us know if you need any help with implementing the suggestions :)

**Comment by PmplCode** [comment]
Hey, @madsnedergaard @VIKTORVAV99 thanks for the suggestions! During this week I'll try to implement this solution.

On the exchange tooltips I haven't seen any style for the position. I'll to figure out how to apply the conditions.

Thanks and we stay in touch!

**Comment by PmplCode** [comment]
Hello, @madsnedergaard @VIKTORVAV99 . Sorry for taking some more time to solve this problem. Today I woke up inspired and I think i got the fix for the exchange tooltips.

If you want to check it out and maybe discuss a better solution or approach for this.

Thanks and stay in touch!

**Comment by PmplCode** [comment]
Hello! How is it going?
Is there anything I forgot to do or anything in general?
Thanks!

**Comment by VIKTORVAV99** [comment]
We have just been a bit busy and unable to prioritize this just yet.

I had hoped to get around to it this weekend that was but other things such as parser changes came up instead (which has a higher priority as it affects all our data).

Hopefully I'll be able to take another look at it soon though.

File: web/src/features/charts/bar-breakdown/utils.ts [hunk 3]
```diff
@@ -192,3 +193,14 @@ export const getExchangesToDisplay = (
...
+export const getHeaderHeight = () => {
+  const [headerHeight, setHeaderHeight] = useState<number>(0);
+
+  useEffect(() => {
+    const height = document.querySelector('header').offsetHeight;
+    setHeaderHeight(height * 1.1);
+  }, [window.innerWidth, window.innerHeight]);
+
+  return headerHeight;
+};
```
Comment (VIKTORVAV99) [inline web/src/features/charts/bar-breakdown/utils.ts:206]:
```suggestion
export const getHeaderHeight = () => {
  const [headerHeight, setHeaderHeight] = useState<number>(0);

  useEffect(() => {
    const height = document.querySelector('header')?.offsetHeight ?? 0;
    setHeaderHeight(height * 1.1);
  }, [window.innerWidth, window.innerHeight]);

  return headerHeight;
};
```
This is to fix a type issue since `document.querySelector()` can return `Null`.

File: web/src/features/exchanges/ExchangeArrow.tsx [hunk 4]
```diff
@@ -64,6 +66,11 @@ function ExchangeArrow({
     r: rotation + (netFlow > 0 ? 180 : 0),
   };
 
+  let tooltipClassNameTest = 'max-h-[256px] max-w-[512px] top-[-76px] hidden md:flex';
```
Comment (VIKTORVAV99) [inline web/src/features/exchanges/ExchangeArrow.tsx:69]: Why is this named `tooltipClassNameTest`?

I don't think it should have test in the name?

**Review by VIKTORVAV99 — COMMENTED** [review]
Just some final notes, but it looks very good!

**Comment by PmplCode** [comment]
Hey @VIKTORVAV99 ,
thanks for your notes, very accurate! 
I've fixed the getHeaderHeight util and refactor the tooltipClassName.

**Comment by VIKTORVAV99** [comment]
> Hey @VIKTORVAV99 , thanks for your notes, very accurate! I've fixed the getHeaderHeight util and refactor the tooltipClassName.

Thanks! I'll take a look as soon as possible!

**Comment by madsnedergaard** [comment]
For a future version (not now) we could consider using https://floating-ui.com/ to handle placement of tooltips, it seems pretty nice and powerful :)

**Comment by PmplCode** [comment]
Looks good, although i have never used floating-ui it seems pretty easy, at least looking at it's documentation.
I'd love to take part of this change.

**Review by madsnedergaard — APPROVED** [review]
Hey again, sorry it took so long to get this reviewed again - to avoid wasting your time I've gone ahead and ensured this PR is up-to-date with `master` (and fixed a small thing with hooks by renaming `getHeaderHeight` to `useHeaderHeight`) :) 

I have tested it locally and it works great, thanks for taking the time to make this change - I promise the turnaround time is usually significantly faster 😅

File: web/src/features/charts/bar-breakdown/utils.ts [hunk 5]
```diff
@@ -194,6 +195,20 @@
...
+export const useHeaderHeight = () => {
+  const [headerHeight, setHeaderHeight] = useState<number>(0);
+
+  useEffect(() => {
+    const headerElement = document.querySelector('header');
+    if (headerElement) {
+      const height = headerElement.offsetHeight;
+      setHeaderHeight(height * 1.1);
+    }
+  }, [window.innerWidth, window.innerHeight]);
```
[the remark this answers is not in the document]
Comment (madsnedergaard) [reply web/src/features/charts/bar-breakdown/utils.ts:207]: Oh, too late bot 😬
