### PR TITLE
Fixed space in kW units

### LINKED ISSUE #5080: Spacing for kW unit is wrong
The spacing for the unit kW is wrong, currently it's `0k W` when it should be `0 kW`.

Image

### PR DESCRIPTION
**Pull request by samotion2**
## Issue 
Closes #5080 

## Description
Fixed wrong space in kW units.

### Preview

Before             |  After
:-------------------------:|:-------------------------:
image  |  image

### CODE REVIEW

File: web/src/utils/formatting.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export const formatPower = function (d: number, numberDigits = DEFAULT_NUM_DIGIT
     return d;
   }
   const power = `${d3.format(`.${numberDigits}s`)(d * 1e6)}W` //Add a space between the number and the unit
-    .replace(/([A-Z])/, ' $1')
+    .replace(/([A-Z, a-z])/, ' $1')
```
Comment (VIKTORVAV99) [inline web/src/utils/formatting.ts:13]: Nice! But you can combine these like this:
```suggestion
    .replace(/([a-zA-Z])/, ' $1')
```

**Review by VIKTORVAV99 — COMMENTED** [review]
Thanks for the PR and welcome to the Electricity Maps contrib repository!

I just have one small suggestion otherwise things look good!

**Review by tonypls — APPROVED** [review]
Great stuff! Thanks for picking this up 🎉
